[server]
port = 8501
enableCORS = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
primaryColor = "#1e3a8a"           # Azul marino profundo (muy elegante)
backgroundColor = "#f8fafc"        # Gris hielo muy claro
secondaryBackgroundColor = "#e2e8f0"  # Gris Francia claro para sidebars
textColor = "#1e293b"             # Gris antracita (muy profesional)
font = "sans serif"               # Fuente limpia

[client]
showErrorDetails = true